name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@master
      with:
        path: ./

    - uses: actions/upload-artifact@v2
      with:
        name: compare-consumer-offsets
        path: src/dist/windows
