name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install deps
      run: sudo apt-get -y install libxml2-dev libxslt-dev

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: ./

    - uses: actions/upload-artifact@v2
      with:
        name: compare-consumer-offsets
        path: ./dist/linux
